# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_davidneak'
    repositoryName: 'DataBaseDPD/DataBaseManagement'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'manual'
    assets: |
      $(Build.Repository.LocalPath)\DBConsole\obj\Release\DBConsole.exe
      $(Build.Repository.LocalPath)\DataBaseDPD\bin\Release\DataBaseDPD.dll
      $(Build.Repository.LocalPath)\Client\bin\Release\netcoreapp3.1\Client.exe
      $(Build.Repository.LocalPath)\Client\bin\Release\netcoreapp3.1\Client.dll
      $(Build.Repository.LocalPath)\Bundler2\bin\Release\Bundler2.exe
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
